version: '3'

services:
  mysql_fface:
    image: mysql:latest
    restart: always
    ports:
      - 3013:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysql_fface
      MYSQL_USER: 
      MYSQL_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - 8113:80
    environment:
      PMA_HOST: mysql_fface
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root

volumes:
  db_data:
