#server:
# port: 1313
#
#spring:
# h2:
#   console.enabled: true
# jpa:
#   show-sql: true
# hibernate:
#   ddl-auto: create
# datasource:
#   url: jdbc:h2:mem:testDB
# username: sa
# password:
#   driver-class-name: org.h2.Driver
# main:
#   allow-circular-references: true




 server:
   port: 1313

 spring:
   datasource:
     driver-class-name: com.mysql.cj.jdbc.Driver
     username: root
     password: root
     url: jdbc:mysql://localhost:3013/mysql_fface
   main:
     allow-circular-references: true

## Specify the path of the OpenAPI documentation
 springdoc:
   api-docs:
     path: /api-docs
   swagger-ui:
     path: /swagger-ui.html
     enabled: true

#security:
#  ignored: /**

#choice:
#  security:
#    enabled: false
##    authorize-mode: NONE
